import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  allowedDevOrigins: ["192.168.56.1"],
  async redirects() {
    return [
      { source: "/services/ai-video-production/automotive", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/ai-video-production/brand-films", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/ai-video-production/corporate-internal", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/ai-video-production/localization", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/ai-video-production/performance-ads", destination: "/services/ad-creative", permanent: true },
      { source: "/services/ai-video-production/product-commercials", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/ai-video-production/product-launch", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/ai-video-production/real-estate", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/ai-video-production/saas-explainers", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/ai-video-production/social-reels", destination: "/services/social-creative", permanent: true },
      { source: "/services/ai-video-production/ugc-style-ads", destination: "/services/ad-creative", permanent: true },
      { source: "/services/ad-creative/key-visuals", destination: "/services/ad-creative", permanent: true },
      { source: "/services/ad-creative/static-ads", destination: "/services/ad-creative", permanent: true },
      { source: "/services/ad-creative/testing-variants", destination: "/services/ad-creative", permanent: true },
      { source: "/services/audio/ai-voiceover", destination: "/services/audio", permanent: true },
      { source: "/services/audio/audio-ads", destination: "/services/audio", permanent: true },
      { source: "/services/audio/music-sound-design", destination: "/services/audio", permanent: true },
      { source: "/services/creative-strategy/campaigns", destination: "/services/creative-strategy", permanent: true },
      { source: "/services/creative-strategy/concept-development", destination: "/services/creative-strategy", permanent: true },
      { source: "/services/creative-strategy/storyboarding", destination: "/services/creative-strategy", permanent: true },
      { source: "/services/post-production/ai-compositing", destination: "/services/post-production", permanent: true },
      { source: "/services/post-production/mastering", destination: "/services/post-production", permanent: true },
      { source: "/services/post-production/motion-graphics", destination: "/services/post-production", permanent: true },
      { source: "/services/post-production/video-editing", destination: "/services/post-production", permanent: true },
      { source: "/services/product-visuals/ecommerce", destination: "/services/product-visuals", permanent: true },
      { source: "/services/product-visuals/image-libraries", destination: "/services/product-visuals", permanent: true },
      { source: "/services/product-visuals/product-photography", destination: "/services/product-visuals", permanent: true },
      { source: "/services/social-creative/monthly-content", destination: "/services/social-creative", permanent: true },
      { source: "/services/social-creative/repurposing", destination: "/services/social-creative", permanent: true },
      { source: "/solutions/creative-testing", destination: "/solutions/performance-marketing", permanent: true },
      { source: "/solutions/multi-format-campaigns", destination: "/solutions/product-launch", permanent: true },
      { source: "/solutions/always-on-content", destination: "/solutions/monthly-creative-subscription", permanent: true },
      { source: "/solutions/agency-white-label", destination: "/solutions/creative-team-overflow", permanent: true },
      { source: "/solutions/localization-global", destination: "/solutions/product-launch", permanent: true },
      { source: "/solutions/creative-automation", destination: "/solutions/performance-marketing", permanent: true },
      { source: "/solutions/dynamic-creative", destination: "/solutions/performance-marketing", permanent: true },
      { source: "/solutions/performance-testing", destination: "/solutions/performance-marketing", permanent: true },
      { source: "/solutions/paid-social-scale", destination: "/solutions/performance-marketing", permanent: true },
      { source: "/solutions/ugc-style-content", destination: "/solutions/performance-marketing", permanent: true },
      { source: "/solutions/brand-films-cinematic", destination: "/solutions/product-launch", permanent: true },
      { source: "/solutions/audio-ads-streaming", destination: "/solutions/product-launch", permanent: true },
      { source: "/solutions/by-industry/consumer-goods", destination: "/industries", permanent: true },
      { source: "/solutions/by-industry/gaming-apps", destination: "/industries", permanent: true },
      { source: "/solutions/by-industry/luxury-fashion", destination: "/industries", permanent: true },
      { source: "/solutions/by-industry/travel-hospitality", destination: "/industries", permanent: true },
      { source: "/industries/automotive-mobility", destination: "/industries", permanent: true },
      { source: "/industries/beauty-skincare", destination: "/industries", permanent: true },
      { source: "/industries/consumer-electronics", destination: "/industries", permanent: true },
      { source: "/industries/dtc-ecommerce", destination: "/industries", permanent: true },
      { source: "/industries/fashion-lifestyle", destination: "/industries", permanent: true },
      { source: "/industries/food-beverage", destination: "/industries", permanent: true },
      { source: "/industries/real-estate", destination: "/industries", permanent: true },
      { source: "/industries/saas-technology", destination: "/industries", permanent: true },
      { source: "/community/afin", destination: "/about", permanent: true },
      { source: "/trust/responsible-ai", destination: "/trust/ai-and-ip", permanent: true },
      { source: "/privacy", destination: "/privacy-policy", permanent: true },
      { source: "/legal/privacy-policy", destination: "/privacy-policy", permanent: true },
      { source: "/accessibility", destination: "/legal/accessibility", permanent: true },
      { source: "/legal/dpa", destination: "/contact", permanent: true },
      { source: "/legal/msa", destination: "/contact", permanent: true },
      { source: "/legal/subprocessors", destination: "/contact", permanent: true },
      { source: "/how-it-works/onboarding", destination: "/how-it-works", permanent: true },
      { source: "/how-it-works/quality-assurance", destination: "/how-it-works/ai-creative-pipeline", permanent: true },
      { source: "/how-it-works/revisions-delivery", destination: "/how-it-works", permanent: true },
      { source: "/pricing/monthly-plans", destination: "/pricing", permanent: true },
      { source: "/pricing/pilot", destination: "/pricing", permanent: true },
      { source: "/resources", destination: "/blog", permanent: true },
      { source: "/guides", destination: "/blog", permanent: true },
      { source: "/playbooks", destination: "/blog", permanent: true },
      { source: "/reports", destination: "/blog", permanent: true },
      { source: "/events", destination: "/blog", permanent: true },
      { source: "/glossary", destination: "/help", permanent: true },
      { source: "/compare/traditional-production", destination: "/compare/vs-traditional-production", permanent: true },
      { source: "/compare/ai-tools", destination: "/compare/vs-ai-tools", permanent: true },
      { source: "/compare/agencies", destination: "/compare/vs-traditional-production", permanent: true },
      { source: "/compare/freelancers", destination: "/compare/vs-traditional-production", permanent: true },
    ];
  },
};

export default nextConfig;